export const players = [
  {
    slug: "michael-van-gerwen",
    name: "Michael van Gerwen",
    nickname: "Mighty Mike",
    birthday: "April 25 1989",
    nationality: "Netherlands",
    hometown: "Vlijmen",
    handiness: "Right",
    darts: "21.5g Winmau ",
    description: "A teenage wonderkid when he broke through to win the 2006 World Masters in the BDO, the Dutchman waited six years to pick up his next televised title at the 2012 World Grand Prix, a victory which sparked a golden run of success. Van Gerwen lifted three World Championship crowns in 2014, 2017 and 2019 during his eight-year spell as world number one, amassing over 140 PDC titles in the process.The Dutchman completed the full set of televised PDC titles in October 2019 when he won the Champions League in Leicester – the first and only player to achieve this feat.",
    playerImage: "/images",
    worldRanking: 3,
    titles: []
  },
  {
    slug: "michael-smith",
    name: "Michael Smith",
    nickname: "Bully Boy",
    birthday: "September 18 1990",
    nationality: "England",
    hometown: "St. Helens",
    handiness: "Right",
    darts: "22g Unicorn",
    description: "The winner of 16 PDC ranking events, Smith also boasts two World Series titles to his name, including the 2022 US Darts Masters in New York.",
    playerImage: "/images",
    worldRanking: 1,
    titles: []
  },
  {
    slug: "peter-wright",
    name: "Peter Wright",
    nickname: "Snakebite",
    birthday: "March 10 1970",
    nationality: "Scotland",
    hometown: "Mendham",
    handiness: "Right",
    darts: "22g Red Dragon",
    description: "Originally a Lakeside qualifier in 1995, Wright’s run to the 2014 World Championship marked his PDC breakthrough, and his 2017 UK Open success ended a 20-year wait for glory.",
    playerImage: "/images",
    worldRanking: 2,
    titles: []
  },
  {
    slug: "gerwyn-price",
    name: "Gerwyn Price",
    nickname: "The Iceman",
    birthday: "March 07 1985",
    nationality: "Welsh",
    hometown: "Markham",
    handiness: "Right",
    darts: "24 g Red Dragon",
    description: "The former rugby professional rose consistently up the ranks before securing his maiden televised crown at the 2018 Grand Slam of Darts, his first of three triumphs in Wolverhampton.",
    playerImage: "/images",
    worldRanking: 4,
    titles: []
  },
  {
    slug: "rob-cross",
    name: "Rob Cross",
    nickname: "Voltage",
    birthday: "September 21 1990",
    nationality: "England",
    hometown: "Hastings",
    handiness: "Right",
    darts: "21g Target",
    description: "The former rugby professional rose consistently up the ranks before securing his maiden televised crown at the 2018 Grand Slam of Darts, his first of three triumphs in Wolverhampton.",
    playerImage: "/images",
    worldRanking: 5,
    titles: []
  },
  {
    slug: "luke-humphries",
    name: "Luke Humphries",
    nickname: "Cool Hand Luke",
    birthday: "February 11 1995",
    nationality: "England",
    hometown: "Crewe",
    handiness: "Right",
    darts: "22 gram Red Dragon Red Dragon",
    description: "Following a dominant spell on the Development Tour, Humphries made an immediate impression on his Alexandra Palace in 2018, and he’s reached the quarter-finals in three of his four visits to the capital.",
    playerImage: "/images",
    worldRanking: 6,
    titles: []
  }
];